### ISSUE TITLE
Volunteer application form

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/volunteer-management-software#18]
Please include the following fields in the application page, happy for you to alter and optimise, as long as I can view those details :)

The doc also includes dot point info that should probably be included on the SF volunteer landing page or application page - open to where you think it would fit best. so people know what they are signing up for - maybe similar to an FAQ page like this? http://aunty.mmf.com.au/every-thing/volunteers/

[Strawberry General Volunteer Application Form.docx](https://github.com/volunteer-manage/volunteer-management-software/files/1074327/Strawberry.General.Volunteer.Application.Form.docx)

**Comment by jarvisjohnson** [comment]
@KimPong  - Ah I see why I didn't see this - I won't get a notification unless you 'assign' me or mention me.  You can assign me in the top right.  or mention me like I mentioned you here (otherwise I'm not associated so don't get a notification
