### ISSUE TITLE
Change confirmation email text

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/volunteer-management-software#24]
If you can change the confirmation email so it comes from volunteers@strawberry-fields.com.au
That would be great 

Please change confirmation email to say something like:

To complete your volunteer application for Strawberry Fields 2017, you'll need to confirm your account email. 

You can confirm your email by clicking this link:

If you have any questions about volunteering, please email:
Volunteers@strawberry-fields.com.au

@jarvisjohnson 
If there is any reasons we can't make these changes just lemme know 😊

**Comment by jarvisjohnson** [comment]
Hey so this is slightly tricky - to send an email from that address:

1.  The address needs to exist - Tara has to set it up
2. The application needs to login to that email address to send the email
3. You need to provide the permissions to send from that email within the account.


Can you get onto Tara to get the email setup please and provide a password to me? @KimPong

**Comment by KimPong** [comment]
Hi @jarvisjohnson 

Here is the details for the volunteer email account:

volunteers@strawberry-fields.com.au
Password:
volunteermaster1111
Incoming Server: webcloud1.au.syrahost.com
IMAP Port: 993
POP3 Port: 995
Outgoing Server: webcloud1.au.syrahost.com
SMTP Port: 465

To Access through the portal: https://webmail.au.syrahost.com/login/

**Comment by KimPong** [comment]
Me and my interns run this email account, you can access it to or just let me know what I need to do to set it up! @jarvisjohnson
