### ISSUE TITLE
Alter summary page so that volunteers appear: First Name, Last Name

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/volunteer-management-software#34]
Heya @jarvisjohnson 

If it's possible, can we please change the way volunteers are displayed so that first name comes first?
That way when I export the data it would appear in separate columns as:
First Name | Last Name | Email  etc

THis is the format eventbrite wants for sending out tickets, and it's also a lot easier with Mail merge as you can then include the person's first name in the email eg.
Dear {{First Name}},

Otherwise, do you know a way to separate the data in a spreadsheet without having to do every one manually??

Cheers!

**Comment by jarvisjohnson** [comment]
Yep, done.

As I said, we can create the tickets in the application via the EventBrite API if you like.  Will be pretty straightforward, like you click a button and EventBrite will send tickets out to everyone you have selected... makes sense.

@KimPong

**Comment by KimPong** [comment]
sweet! thanks @jarvisjohnson! I'll just confirm with the eventbrite manager I've been speaking with - as Tara has sent out strict instructions to all department heads about how to request tickets :)

**Comment by KimPong** [comment]
@jarvisjohnson i've emailed Kelly at eventbrite but she's out of office for a couple of days. I'm inclined to just send them the list and let them deal with ticketing. They are getting paid for it. It certainly makes sense and would be a great feature of our portal, but i don't have time to be answering ticket queries if volunteers haven't received them etc and i'm not sure you do either! i'm so flat out trying to get this all done as well as Meredith and Off The Grid!
