### ISSUE TITLE
shift time not updating

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/volunteer-management-software#36]
Hi @jarvisjohnson , when I alter the shift times for each rotation manually, it seems to update. but when you assign people to the shift, the summary on the right hand side doesn't have the correct shift time. is it possible to fix for shift send out ASAP?  I've attached some screenshots to illustrate. xx

<img width="529" alt="screenshot time not updating on sidebar" src="https://user-images.githubusercontent.com/29219132/32261713-7d77983c-bf24-11e7-9717-af66c3136c70.png">

<img width="960" alt="screenshot shift times are correct" src="https://user-images.githubusercontent.com/29219132/32261705-753a4b92-bf24-11e7-87a5-8db7c7ec7726.png">

<img width="960" alt="screenshot shift allocations" src="https://user-images.githubusercontent.com/29219132/32261699-6ded5956-bf24-11e7-8de7-8e2f01759f03.png">

**Comment by KimPong** [comment]
@jarvisjohnson just for some more info, it doesn't seem to matter what i customise the shift time to be, it still comes up on the sidebar as the time it original was, mostly 11am for the first shift listed. 

so cool how i can just select the people and put them in the shift! nice stuff x

**Comment by jarvisjohnson** [comment]
This is done
