### ISSUE TITLE
shift notification email

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/volunteer-management-software#37]
Hi @jarvisjohnson 

if the notification email is being sent via the portal, just wanted to check that the notification email says:

Hi there,

Your shift times for Strawberry Fields 2017 are now available in the portal!

Please check your shift times **here** and be prepared to arrive on time!

Your shift may be in a different department than we originally notified you. We are a sorry this couldn't be helped in some cases. 

**Some important points about completing your shifts:**

- Sign IN and OUT of your shift at the Volunteer Sign in area next to the Info Tent. 
- You must bring a photo ID to sign in and out.
- You must wear your volunteer t-shirt during your shift - please sign in early if you need to collect it from the Volunteer area.
-You will not be able to complete your shift if you are not wearing shoes with an enclosed toe.
- If your shift is with the Gate or Treecreds team, you'll need to be at the Volunteer sign in area half an hour before it starts to ensure we can transport you to the gate area  - this is a long walk from the festival campgrounds. For all other departments, please arrive 15 mins before your shift.

All of these requirements are for your own safety and for the smooth running of the event. Failure to comply with the above points risks the penalty charge for breaching the volunteer agreement.

If you have any questions please get in touch! We'll be happy to help.

Much love,
SF

*****Also, does it work better for you to send directly from the gmail account rather than through the volunteers@strawberry-fields.com.au 
I've been sending emails directly and it seems to work as long as I don't send more than 250 a day.

**Comment by jarvisjohnson** [comment]
I've built this in so emails are ready to send Pong :)

Remember to hold off on sending until as many shifts are assigned as you can, so as not to confuse people with multiple emails for another shift later.
