### ISSUE TITLE
Rotations appearing on page incorrectly 

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/volunteer-management-software#38]
Hey @jarvisjohnson - thought I should explain better if I was a bit rushed before - I hope you can help figure out where it's going wrong!

There are too many rotations appearing on some jobs, even after I have updated the job on the 'create jobs' page and edited the shift start times. I go back into that job and there is often Twice as many rotations as I'd created originally. 

I figure I'm doing something wrong to make this happen? I also can't figure out how to get rid of them, which is making it difficult to see which shifts actually need to be there 😊 Eg. Treecreds Thursday should have 4 and it has 8 rotations.

**Comment by KimPong** [comment]
@jarvisjohnson looking beautiful in the app now - i'll continue withouth removing the unneccessary rotations but lemme know if you're able to include a little delete option at some point!

**Comment by jarvisjohnson** [comment]
You should be able to delete volunteers now :)
