### ISSUE TITLE
app wont allow volunteers to be assigned twice in one day

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/volunteer-management-software#40]
hey pongy! @jarvisjohnson 
in the drop down for gate, traffic and tree creds on Friday, some shifts won't offer any volunteers (or the correct volunteers) to select from. I think this might be because they are already allocated on a shift that day? does the app have some kind of rule that would dictate that? 

Some people have a morning shift and an evening shift so i would need this altered..

Shifts affected 
GATE Thurs/Fri: Friday 5PM 
GATE Thurs/Fri: Friday 6PM

TRAFFIC Thurs/Fri: Friday 7pm
TREECREDS: Thursday 7pm 
TREECREDS: Friday 2.30pm
TREECREDS: Friday 7pm

**Comment by jarvisjohnson** [comment]
Yeah that's right Pong.   I didn't think you'd be putting people in shifts on the same day so I made sure if they already had one, they don't cone up again.

I will change this now.
