### ISSUE TITLE
CHARGE IMMEDIATELY

### ISSUE THREAD

**Issue by KimPong** [volunteer-manage/volunteer-management-software#48]
Hi @jarvisjohnson 

Josephine  Baan
Jelle Knobbe

These two need to be charged the $360 - abandoned shift and subsequently let a $10,000 artwork get tagged. no warning required let's charge asap and hound these two to the death ;)

**Comment by KimPong** [comment]
Please also add these two to the immediate list:


Mia   Stebel
Cara Susskind

thanks @jarvisjohnson

**Comment by KimPong** [comment]
Hey mate, there was a miscommunication with Cara Susskind and Mia Stebel - they don't need to be charged.

**Comment by jarvisjohnson** [comment]
Josephine Baan had insufficient funds.

**Comment by jarvisjohnson** [comment]
Jelle Knobbe charge succeeded

**Comment by jarvisjohnson** [comment]
closing in favour of https://github.com/volunteer-manage/volunteer-management-software/issues/50
